project:
  type: website
  output-dir: docs

website:
  favicon: "images/logo.png"
  page-navigation: true
  title: "ML Handbook"
  description: "Unlock the practical side of Machine Learning with hands-on Colab notebooks and in-depth reports, making ML education accessible and insightful."

  site-url: "https://bsc-iitm.github.io/ML_Handbook/"

  repo-url: https://github.com/bsc-iitm/ML_Handbook
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bsc-iitm/ML_Handbook
        text: "GitHub Repo"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Home"
        contents:
          - href: index.qmd
            text: About
      - text: "---"
      - section: "Preprocessing"
        contents:
          - href: ./pages/Deliverable_1.ipynb
            text: Handling Missing Values
          - section: "Scaling"
            contents:
              - href: ./pages/Scaling multi-dataset multi-algo.ipynb
                text: Overview
              - href: ./pages/standard.ipynb
                text: Standard Scaling
      - section: "Extras"
        contents:
          - href: ./pages/Inductive_Bias.ipynb
            text: Inductive Bias

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual
