project:
  type: website
  output-dir: docs

website:
  favicon: "images/logo.png"
  page-navigation: true
  title: "ML Handbook"
  description: "Unlock the practical side of Machine Learning with hands-on Colab notebooks and in-depth reports, making ML education accessible and insightful."

  site-url: "https://bsc-iitm.github.io/ML_Handbook/"

  repo-url: https://github.com/bsc-iitm/ML_Handbook
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bsc-iitm/ML_Handbook
        text: "GitHub Repo"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Home"
        contents:
          - href: index.qmd
            text: Content
          - href: about.qmd
            text: About
      - text: "---"
      - section: "Preprocessing"
        contents:
          - href: ./pages/dealing_with_missing_values.ipynb
            text: Dealing with missing-values 
          - section: "Scaling"
            contents:
              - href: ./pages/Scaling multi-dataset multi-algo.ipynb
                text: Overview
              - href: ./pages/standard.ipynb
                text: Standard Scaling
      - section: "Observing Data"
        contents:
          - section: "Visualization"
            contents:
              - href: ./pages/vis.ipynb
                text: Overview
              - href: ./pages/vis2.ipynb
                text: Comprehensive Data Visualization
      - section: "Evaluation Metrics"
        contents:
          - href: ./pages/accuracy.ipynb
            text: Accuracy
          - href: ./pages/f1.ipynb
            text: F1 Score
          - href: ./pages/recall.ipynb
            text: Recall
          - href: ./pages/precision.ipynb
            text: Precision
          - href: ./pages/roc.ipynb
            text: ROC-AUC
      - section: "Special Topics in ML"
        contents:
          - href: ./pages/Inductive_Bias.ipynb
            text: Inductive Bias
          - href: ./pages/Ordinal_Classification.ipynb
            text: Ordinal Classification
          - href: ./pages/EM_Algorithm.ipynb
            text: EM Algorithm
          - href: ./pages/Probabilistic_PCA.ipynb
            text: Probabilistic PCA
          - href: ./pages/agg.ipynb
            text: Agglomerative Clustering
      - section: "Case Studies"
        contents:
          - href: ./pages/cirrhosis.ipynb
            text: Predictive Modeling of Patient Status in Primary Biliary Cirrhosis
          - href: ./pages/bank_churn.ipynb
            text: Predicting Bank Customer Churn

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual
