project:
  type: website

website:
  page-navigation: true
  title: "ML_Handbook"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sta210-s22
        text: "GitHub organization"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Home"
        contents:
          - href: index.qmd
            text: About

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual
